### ISSUE TITLE
(Windows) Doesn't seem to output anything

### ISSUE THREAD

**Issue by welcomebrand** [joereynolds/mort#43]
I suspect I've missed something obvious but when I run the default command, mort runs but it doesn't seem to do anything other than say it's scanning. 

MYDIR>mort -f assets/css/screen.css -v
Running mort in verbose mode [Verbosity: 1]
Scanning assets/css/screen.css ...

I've installed ripgrep and everything seems to be where it should be but I was expecting to see output of rules I could remove. 

Any thoughts on where I might look to fix?

**Comment by joereynolds** [comment]
Hey @welcomebrand,

What's the output of `ls .-la` in the root of where you're scanning?

You could have a tags file or something else that's indexed the entire project, in that case `mort` won't find anything

**Comment by welcomebrand** [comment]
I'm trying to run it on an Umbraco CMS powered site so this is my root dir contents: 

`
08/05/2018  16:19    <DIR>          .
08/05/2018  16:19    <DIR>          ..
30/03/2017  13:58    <DIR>          .sass-cache
22/03/2017  16:07                54 AD7F8C2F830A65ECBB86E5E71B582960.txt
22/03/2017  16:08             2,239 apple-touch-icon-precomposed.png
22/03/2017  16:08             2,246 apple-touch-icon.png
22/03/2017  16:07    <DIR>          App_Browsers
24/05/2018  14:19    <DIR>          App_Data
07/06/2017  13:15    <DIR>          App_Plugins
15/06/2017  19:28    <DIR>          aspnet_client
22/03/2017  16:08    <DIR>          assets
22/03/2017  16:52                33 astrum-config.json
02/03/2018  12:21    <DIR>          bin
02/03/2018  12:21    <DIR>          Config
19/02/2018  15:14    <DIR>          css
22/03/2017  16:08               152 default.aspx
22/03/2017  16:08            15,086 favicon.ico
22/03/2017  16:07                89 Global.asax
22/03/2017  16:08                53 google021c3e2f34d5e49e.html
18/05/2018  11:55             4,514 Gruntfile.js
22/03/2017  16:08               122 humans.txt
15/05/2018  15:31    <DIR>          media
30/05/2018  12:31    <DIR>          node_modules
22/03/2017  16:08               443 package.json
22/03/2017  16:08               566 packages.config
02/11/2017  17:59    <DIR>          pattern-library
22/03/2017  16:08               344 robots.txt
22/03/2017  16:07    <DIR>          Umbraco
22/03/2017  16:08    <DIR>          Umbraco_Client
25/05/2018  15:15    <DIR>          Views
02/03/2018  12:49            30,747 Web.config
02/11/2017  17:53            30,747 Web.dev.config
08/05/2018  16:19            30,868 Web.live.config
22/03/2017  16:08    <DIR>          xslt
15/05/2017  14:08            15,902 _handbook.html
05/05/2017  09:02            36,057 _library.html
              18 File(s)        170,262 bytes
`

**Comment by joereynolds** [comment]
Okay, well nothing really sticks out to me there, the only thing I can think of is that it's a "Windows thing".

I'll need to investigate this as it's only been tested on Ubuntu.

Thanks for the heads up, if you find out anything else, let me know!

**Comment by joereynolds** [comment]
Hey @welcomebrand ,

I just tried it on a windows machine and it seems to be working. 
Can you force the use of `git grep` for me and let me know if that helps?

```
mort -vvv -f your-file -p gitgrep
```

**Comment by willans** [comment]
I'm trying to use this on macOS High Sierra and I'll I'm getting is the following message, then it does nothing

    Scanning public/assets/frontend/css/site.css ...

**Comment by joereynolds** [comment]
Hey @willans 

Same questions:

- What's the output of ls -la in the root of where you're scanning?
- What version of node are you on?

Can you do me a favour and run (Note the 3 v's):
```
mort -f assets/css/screen.css -vvv
```

Can you force the use of git grep for me and let me know if that helps?
```
mort -vvv -f your-file -p gitgrep
```

**Comment by joereynolds** [comment]
Hey @willans and @welcomebrand,

I pushed a change before to print "Done!" once `mort` has finished searching.
This makes it more apparent when mort has finished (otherwise it just looks like its paused).

Hopefully that may help you guys out though I suspect your problems aren't related to that fix I've added (what I've added was needed anyway)

https://github.com/joereynolds/mort/commit/0e3bc58a6c757500b3fbd5bf5567516fa4ee8c26

**Comment by joereynolds** [comment]
Hey @welcomebrand and @willans,

I've released binaries for linux, mac, and windows, so they might be another avenue for you to explore if you're still having trouble.

They're available on the [releases page](https://github.com/joereynolds/mort/releases)

Thanks!
